name: Build and Test .NET

on:
  pull_request:
    branches: 
        - Assignment**


jobs:
  build-and-test:
    name: Run Shared Build and Test Workflow
    uses: IntelliTect-Samples/EWU-CSCD371-2024-Winter/.github/workflows/build-and-test.yml@main
    with:
          working-directory: './PrincessBrideTrivia/'
